### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lukasoppermann** [lukasoppermann/design-tokens#2]
# Roadmap
### Colors
- [x] solid fills only
- [x] only one fill per color token

### Borders
- [x] solid fills only
- [x] only one fill per token

### Grids
- [x] support multiple grids

### Sizes
- [x] only width is used

### Effects
- [x] support multiple effects

## Version 1.0
- [x] ignore styles that have a name starting with `_`

### Colors
- [x] support gradients

### Workflow
- [x] provide amazon style directory transformers for css & sass

### Primitives ?
- [ ] should primitives be included and used to build tokens? e.g.  `font-family`, `color` (without opacity), `typescale` (separated from font itself)
- [ ] allow tokens that can be styles (e.g. text, color, etc.) to be created from elements as well?
  - [ ] this would allow to use core styles in other styles (e.g. `core-color-primary` could be used as the color for `button-color-primary`)
  - [ ] may allow for granular tokens, e.g. `font-family` or only `font-size`

### Colors
- [x] support multiple fills?

### Borders
- [ ] support gradients
- [ ] support multiple fills?
- [ ] create reference if design token color are used

### Sizes
Include different sizes, maybe the ones below (?):
- [x] spacers (only width)
- [ ] padding (autolayout)
- [ ] width
- [ ] height

### Others
- [x] Maybe include motion properties?
- [ ] How can properties that are not applicable to figma be created and exported in figma?

### Settings
- [ ] setting to choose if units should be added or not (`12px` or just `12`)
- [ ] setting to include top level prefix (e.g. `token` or `style`)
- [ ] setting to include category level prefix (e.g. `color` or `typography`)
- [ ] setting to only import selected tokens e.g. only `colors`
- [x] toggle between not converting styles prefixed with `_` and only converting styles that are subitem of `_tokens`

### Workflow
- [x] provide webhook / push & example of repo that converts via github action
- [ ] allow for yaml files (https://www.npmjs.com/package/yamljs)

### Testing
- [x] implement tests #4

**Comment by uptonking** [comment]
I really want the feature of Export Design Token File By Type, for example, `_tokens/sizes` Frame exported to `sizes.json`, `_tokens/colors` exported to `colors.json`.   
In this way, we can export multiple json files. 
This feature can be integrated with style dictionary v3 to [automatically generate 1:1 token files based on a custom filter](https://github.com/amzn/style-dictionary/pull/481).

That is `_tokens/colors` > `colors.json` > `colors.css`. 
more idiomatic to dev.

**Comment by lukasoppermann** [comment]
Hey @uptonking can you send a PR to include this?

**Comment by CrispoColombo** [comment]
Would it be possible to include elevation/dropshadow values?

**Comment by lukasoppermann** [comment]
> Would it be possible to include elevation/dropshadow values?

This is currently working via effect styles. Do you have any issue with that as to why you feel it would need to also be included as a custom token?
